#!/bin/bash

starter() {
  local apps=(htop zsh fzf exa jq neovim stow bat rofi xsetroot xclip flameshot xset ripgrep cmake make fd-find)
  local configs=(git htop nvim scripts x11 zsh) 

  # Installing all applications and other stuff
  dnfInstaller "${apps[@]}"

  # Installing dev tools, packages and utils
  devToolsInstaller

  # Simplele and easy
  linker "${configs[@]}"

  if [ "$SHELL" != "$(which zsh)" ]; then
    echo ">> Activating ZSH shell for $USER, for the next login"
    chsh -s /usr/bin/zsh "$USER"
  fi

  exit 1
}

exists() {
  command -v "$1" >/dev/null 2>&1
}

dnfInstaller() {
  echo ">> Installing applications: ${*}"
  sudo dnf install -y "$@"
}

devToolsInstaller() {
  ohmyzshInstaller
  nvmInstaller
  sdkmanInstaller
  rustupInstaller
  pyenvInstaller
}

linker() {
  local array=("$@")

  echo ">> Linking config files: ${*}"
  cd $HOME/Sources/Own/dotfiles

  for config in "${array[@]}"; do
    if [ "$config" = "zsh" ]; then
      stow --adopt -t "$HOME" "$config"
    else
      stow -t "$HOME" "$config"
    fi
  done
}

ohmyzshInstaller() {
  if [ -d "${HOME}/.oh-my-zsh" ]; then
    echo "Info: oh-my-zsh already installed."
  fi
  
  git clone https://github.com/ohmyzsh/ohmyzsh.git ~/.oh-my-zsh
}

nvmInstaller() {
  if [ -d "${HOME}/.nvm/.git" ];then
    echo "Info: nvm already installed."
    return 1
  fi

  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
}

pyenvInstaller() {
  if [ -d "${HOME}/.pyenv" ];then
    echo "Info: pyenv already installed."
    return 1
  fi

  curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
}

sdkmanInstaller() {
  if [ -d "${HOME}/.sdkman" ]; then
    echo "Info: sdkman already installed."
    return 1
  fi

  curl -s "https://get.sdkman.io" | zsh
}

rustupInstaller() {
  if [ -d "${HOME}/.rustup" ]; then
    echo "Info: rustup already installed."
    return 1
  fi

  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
}

starter
