#!/bin/bash

starter() {
  local apps=(alacritty htop zsh fzf exa jq neovim stow bat arandr rofi nitrogen xorg-xsetroot xclip flameshot xorg-xset)
  local configs=(alacritty git htop nvim scripts x11 zsh leftwm eww)

  # Installing all applications and other stuff
  pacmanInstaller "${apps[@]}"

  # Installing other packages and utils manually
  nvmInstaller
  sdkmanInstaller
  rustupInstaller
  wiredInstaller

  # Simplele and easy
  linker "${configs[@]}"

  if [ "$SHELL" != "$(which zsh)" ]; then
    echo ">> Activating ZSH shell for $USER, for the next login"
    chsh -s /usr/bin/zsh "$USER"
  fi

  exit 1
}

exists() {
  command -v "$1" >/dev/null 2>&1
}

pacmanInstaller() {
  echo ">> Installing applications: ${*}"
  sudo pacman -S --noconfirm --needed --noprogressbar "$@"

  if [ ! -d ~/.oh-my-zsh ]; then
    echo ">> Installing extra packages/plugins/tools: oh-my-zsh"
    git clone https://github.com/ohmyzsh/ohmyzsh.git ~/.oh-my-zsh
  fi
}

linker() {
  local array=("$@")

  echo ">> Linking config files: ${*}"
  cd $HOME/Sources/dotfiles

  for config in "${array[@]}"; do
    if [ "$config" = "zsh" ]; then
      stow --adopt -t "$HOME" "$config"
    else
      stow -t "$HOME" "$config"
    fi
  done
}

nvmInstaller() {
  if [ -d "${HOME}/.nvm/.git" ];then
    echo "Info: nvm already installed."
    return 1
  fi

  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
}

sdkmanInstaller() {
  if [ -d "${HOME}/.sdkman" ]; then
    echo "Info: sdkman already installed."
    return 1
  fi

  curl -s "https://get.sdkman.io" | zsh
}

rustupInstaller() {
  if [ -d "${HOME}/.rustup" ]; then
    echo "Info: rustup already installed."
    return 1
  fi

  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
}

wiredInstaller() {
  if [ -d "${HOME}/Sources/NotMine/wired-notify" ]; then
    echo "Info: wired already installed."
    return 1
  fi

  git clone https://github.com/Toqozz/wired-notify.git ${HOME}/Sources/NotMine/wired-notify
  cd ${HOME}/Sources/NotMine/wired-notify && cargo build --release
  sudo install -s -Dm755 ${HOME}/Sources/NotMine/wired-notify/target/release/wired -t /usr/bin
}

starter
