source ~/.config/nvim/settings/global.vim
source ~/.config/nvim/settings/startify.vim
source ~/.config/nvim/settings/coc.vim
source ~/.config/nvim/settings/nerdtree.vim
source ~/.config/nvim/settings/rainbow-parentheses.vim
source ~/.config/nvim/settings/nerdtree-syntax-highlight.vim
source ~/.config/nvim/settings/devicons.vim
source ~/.config/nvim/settings/airline.vim
source ~/.config/nvim/settings/easy-align.vim
source ~/.config/nvim/settings/nerdtree-git.vim
