local utils = require("me.utils")
local spec = utils.spec

-- General configurations
require("me.options")
require("me.keymaps")
require("me.autocmds")

-- Plugins
spec("me.plugins.alpha")
spec("me.plugins.autopairs")
spec("me.plugins.autotag")
spec("me.plugins.breadcrumbs")
spec("me.plugins.bufdelete")
spec("me.plugins.cmp")
spec("me.plugins.colorscheme")
spec("me.plugins.comment")
spec("me.plugins.dap")
spec("me.plugins.devicons")
spec("me.plugins.diffview")
spec("me.plugins.gitsigns")
spec("me.plugins.illuminate")
spec("me.plugins.indent-blankline")
spec("me.plugins.lspconfig")
spec("me.plugins.lualine")
spec("me.plugins.mason")
spec("me.plugins.neodev")
spec("me.plugins.neogit")
spec("me.plugins.null-ls")
spec("me.plugins.nvim-navic")
spec("me.plugins.nvim-tree")
spec("me.plugins.plenary")
spec("me.plugins.schemastore")
spec("me.plugins.telescope")
spec("me.plugins.toggleterm")
spec("me.plugins.treesitter")
spec("me.plugins.which-key")

-- Plugins - Extras
spec("me.plugins.extras.autosession")
spec("me.plugins.extras.bqf")
spec("me.plugins.extras.colorizer")
spec("me.plugins.extras.copilot")
spec("me.plugins.extras.crates")
spec("me.plugins.extras.dressing")
spec("me.plugins.extras.eyeliner")
spec("me.plugins.extras.fidget")
spec("me.plugins.extras.fugitive")
spec("me.plugins.extras.gitlinker")
spec("me.plugins.extras.harpoon")
spec("me.plugins.extras.jaq")
spec("me.plugins.extras.matchup")
spec("me.plugins.extras.modicator")
spec("me.plugins.extras.neoscroll")
spec("me.plugins.extras.neotab")
spec("me.plugins.extras.noice")
spec("me.plugins.extras.nui")
spec("me.plugins.extras.numb")
spec("me.plugins.extras.package-info")
spec("me.plugins.extras.persistence")
spec("me.plugins.extras.rainbow")
spec("me.plugins.extras.rustacean")
spec("me.plugins.extras.surround")
spec("me.plugins.extras.trouble")
spec("me.plugins.extras.tsc")
spec("me.plugins.extras.typescript-tools")
spec("me.plugins.extras.ufo")

-- Load Lazy and all plugins declared before
require("me.lazy")

