#!/bin/bash

laptop="w0rk"
desktop="g0rr10n"

case $HOSTNAME in
  "$laptop")
    whereiam="laptop"
    ;;
  "$desktop")
    whereiam="desktop"
    ;;
  *)
    whereiam="I don't know... :("
    ;;
esac

echo $whereiam
exit 0
